name: Deploy MkDocs Material

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config --local user.email "75377334+tuandung222@users.noreply.github.com"
          git config --local user.name "tuandung222"

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force --clean --verbose
